#
# Makefile for Unisys SPAR drivers
#
obj-$(CONFIG_UNISYS_VISORUTIL)		+= visorutil/
obj-$(CONFIG_UNISYS_VISORCHANNEL)	+= visorchannel/
obj-$(CONFIG_UNISYS_VISORCHIPSET)	+= visorchipset/
obj-$(CONFIG_UNISYS_UISLIB)		+= uislib/
obj-$(CONFIG_UNISYS_VIRTPCI)		+= virtpci/
obj-$(CONFIG_UNISYS_VIRTHBA)		+= virthba/
obj-$(CONFIG_UNISYS_VISORCLIENTBUS)	+= visorclientbus/
obj-$(CONFIG_UNISYS_VISORBUS)		+= visorbus/
obj-$(CONFIG_UNISYS_VISORDIAG)		+= visordiag/
obj-$(CONFIG_UNISYS_VIRTNIC)		+= virtnic/
obj-$(CONFIG_UNISYS_VISORNOOP)		+= visornoop/
obj-$(CONFIG_UNISYS_VISORNIC)		+= visornic/
obj-$(CONFIG_UNISYS_VISORSERIAL)	+= visorserial/
obj-$(CONFIG_UNISYS_VISORVIDEOCLIENT)	+= visorvideoclient/
obj-$(CONFIG_UNISYS_VISORCONINCLIENT)	+= visorconinclient/
obj-$(CONFIG_UNISYS_SPARSTOP)		+= sparstopdriver/
